config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :gossip
  resources :user
  get 'team', to: 'static#team'
  get 'contact', to: 'static#contact'
  get 'welcome/:user_name', to: 'welcome#show'
  root 'gossip#index'

  # Defines the root path route ("/")
  # root "articles#index"
end

#Rails.application.routes.draw do
#  root 'static#home'
#  get 'team', to: 'static#team'
#  get 'contact', to: 'static#contact'
#  get 'welcome/:user_name', to: 'static#welcome'
#  get 'gossip/:gossip_id', to: 'static#gossip', as: 'gossip_pre'
#
#  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
#
#  # Defines the root path route ("/")
#  # root "articles#index"
#end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
  has_many :gossips, through: :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
  has_many :likes, as: :imageable
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :intertags
  has_many :comments
  has_many :likes, as: :imageable
  has_many :tags, through: :intertags
  validates :content, presence: true
  validates :title, presence: true, length: {minimum: 3, maximum: 14}
end

app/models/intertag.rb
# Correspond à Join Tag et Gossip
class Intertag < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :imageable, polymorphic: true
  belongs_to :user
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :intertags
  has_many :gossips, through: :intertags
  has_many :users, through: :gossips
end

app/models/user.rb
class User < ApplicationRecord
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :likes
  has_many :tags, through: :gossips
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true,
  format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/ } #/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController

  def index
    @all_gossips = Gossip.all
    @all_users = User.all
  end

  def new
    @gossip = Gossip.new
  end
  
  def create
    @gossip = Gossip.new('user_id' => User.all.sample.id,
                   'title' => params[:title],
                   'content' => params[:content])
    if @gossip.save
      redirect_to root_path(success: true)
    else
      render :new
    end
  end

  def edit
  end

  def show
    @current_gossip = Gossip.find(params[:id].to_i)
  end

  def update
  end

  def destroy
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def contact
  end

  def team
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end

  def create
  end

  def new
  end

  def edit
  end

  def show
    @current_user = User.find(params[:id].to_i)
  end

  def update
  end

  def destroy
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
    @user = params[:user_name]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gossip/create.html.erb
<h1>Gossip#create</h1>
<p>Find me in app/views/gossip/create.html.erb</p>

app/views/gossip/destroy.html.erb
<h1>Gossip#destroy</h1>
<p>Find me in app/views/gossip/destroy.html.erb</p>

app/views/gossip/edit.html.erb
<h1>Gossip#edit</h1>
<p>Find me in app/views/gossip/edit.html.erb</p>

app/views/gossip/index.html.erb
<body>

<% if params[:success] %>
  <div class="alert alert-success" role="alert">
    Votre potin a été créé avec succès !
  </div>
<% end %>

<div class="jumbotron">
        <div class="container text-center justify-content-center">
          <h1 class="display-3">Bienvenue sur notre magnifique site de potins !</h1>
          <p><%= link_to "Cliquez ici pour creer votre propre potin.", new_gossip_path, :class => "btn btn-dark"%></p>
        </div>
      </div>


<div class="container text-center justify-content-center">
<h2>Voici la liste de tous les potins : </h2><br/>
    <%@all_gossips.each do |elem|%>
    <%=elem.user.first_name %> : <%= elem.title%>
    <br/> <%= link_to "Cliquez ici pour lire le potin.", gossip_path(elem.id), :class => " btn btn-dark"%> <br/>
    <%end%>
</div>
</body>

app/views/gossip/new.html.erb
<body data-turbo="false">
  <%= yield %> 

<h1>Gossip#new</h1>
<p>Find me in app/views/gossip/new.html.erb</p>
<% if @gossip.errors.any? %>
<div class="alert alert-danger" role="alert">
  <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @gossip.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div>
  <%= form_tag url_for(action: 'create'), method: "post" do %>
    <%= label_tag 'Title' %>
    <%= text_field_tag 'title', @gossip.title %>
    <br /> <br />
    <%= label_tag 'Content' %>
    <%= text_area_tag 'content', @gossip.content %>
    <br /> <br />
    <br /> <br />
    <%= submit_tag "Create Post" %>
  <% end %>
</div>
</body>

app/views/gossip/show.html.erb
<div class="container text-center justify-content-center">

<h1>Bienvenue sur la page Gossip n°<%=@current_gossip.id %></h1>

<p>Auteur du Potin : <%=@current_gossip.user.first_name %> </p>
<p>Titre du Potin : <%=@current_gossip.title %></p>
<p>Date de creation du Potin : <%=@current_gossip.created_at %></p>
<p>Potin : <%=@current_gossip.content %></p>

<p>Lien vers la page de l'auteur : <%= link_to "Cliquer ici.", user_path(@current_gossip.user.id), :class => "nav-link"%></p>
</div>

app/views/gossip/update.html.erb
<h1>Gossip#update</h1>
<p>Find me in app/views/gossip/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Potins</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
     <%= link_to "Navbar", root_path, :class => "navbar-brand"%>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <%= link_to "Home", root_path, :class => "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Contact", contact_path, :class => "nav-link"%>
          </li>
          <li class="nav-item">
             <%= link_to "Team", team_path, :class => "nav-link" %>
          </li>
        </ul>
      </div>
    </nav>
  </head>

  <body>
    <%= yield %>

  </body>
</html>

app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/user/destroy.html.erb
<h1>User#destroy</h1>
<p>Find me in app/views/user/destroy.html.erb</p>

app/views/user/edit.html.erb
<h1>User#edit</h1>
<p>Find me in app/views/user/edit.html.erb</p>

app/views/user/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

app/views/user/new.html.erb
<h1>User#new</h1>
<p>Find me in app/views/user/new.html.erb</p>

app/views/user/show.html.erb
<div class="container text-center justify-content-center">

<h1>Bienvenu sur le profil de <%= @current_user.first_name %></h1>

<p>Prénom : <%= @current_user.first_name %> </p>
<p>Nom : <%= @current_user.last_name %>  </p>
<p>Âge : <%= @current_user.age %>  </p>
<p>Email : <%= @current_user.email %>  </p>
<p>Habite : <%= @current_user.city.name %>  </p>
<p>Description : <%= @current_user.description %>  </p>
<p>Find me in app/views/static/index.html.erb</p>

</div>

app/views/user/update.html.erb
<h1>User#update</h1>
<p>Find me in app/views/user/update.html.erb</p>

app/views/welcome/index.html.erb
<h1>Coucou <%= @user %></h1>

app/views/welcome/show.html.erb
<h1>Coucou <%= @user %></h1>